# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Home Match' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Home Match
  pod 'AlamofireImage'
  pod 'lottie-ios' 

  target 'Home MatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Home MatchUITests' do
    # Pods for testing
  end

end
